
import { Language } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'Engleski', englishName: 'English' },
  { code: 'es', name: 'Španski', englishName: 'Spanish' },
  { code: 'fr', name: 'Francuski', englishName: 'French' },
  { code: 'de', name: 'Nemački', englishName: 'German' },
  { code: 'it', name: 'Italijanski', englishName: 'Italian' },
  { code: 'pt', name: 'Portugalski', englishName: 'Portuguese' },
  { code: 'ru', name: 'Ruski', englishName: 'Russian' },
  { code: 'zh', name: 'Kineski', englishName: 'Chinese' },
  { code: 'ja', name: 'Japanski', englishName: 'Japanese' },
  { code: 'ko', name: 'Korejski', englishName: 'Korean' },
  { code: 'ar', name: 'Arapski', englishName: 'Arabic' },
  { code: 'hi', name: 'Hindi', englishName: 'Hindi' },
  { code: 'bn', name: 'Bengalski', englishName: 'Bengali' },
  { code: 'pa', name: 'Pandžapski', englishName: 'Punjabi' },
  { code: 'jv', name: 'Javanski', englishName: 'Javanese' },
  { code: 'ms', name: 'Malajski', englishName: 'Malay' },
  { code: 'tr', name: 'Turski', englishName: 'Turkish' },
  { code: 'vi', name: 'Vijetnamski', englishName: 'Vietnamese' },
  { code: 'th', name: 'Tajlandski', englishName: 'Thai' },
  { code: 'nl', name: 'Holandski', englishName: 'Dutch' },
  { code: 'sv', name: 'Švedski', englishName: 'Swedish' },
  { code: 'da', name: 'Danski', englishName: 'Danish' },
  { code: 'fi', name: 'Finski', englishName: 'Finnish' },
  { code: 'no', name: 'Norveški', englishName: 'Norwegian' },
  { code: 'pl', name: 'Poljski', englishName: 'Polish' },
  { code: 'cs', name: 'Češki', englishName: 'Czech' },
  { code: 'hu', name: 'Mađarski', englishName: 'Hungarian' },
  { code: 'ro', name: 'Rumunski', englishName: 'Romanian' },
  { code: 'el', name: 'Grčki', englishName: 'Greek' },
  { code: 'he', name: 'Hebrejski', englishName: 'Hebrew' },
  { code: 'id', name: 'Indonežanski', englishName: 'Indonesian' },
  { code: 'uk', name: 'Ukrajinski', englishName: 'Ukrainian' },
  { code: 'hr', name: 'Hrvatski', englishName: 'Croatian' },
  { code: 'sl', name: 'Slovenački', englishName: 'Slovenian' },
  { code: 'bg', name: 'Bugarski', englishName: 'Bulgarian' },
  { code: 'sk', name: 'Slovački', englishName: 'Slovak' },
  { code: 'lt', name: 'Litvanski', englishName: 'Lithuanian' },
  { code: 'lv', name: 'Letonski', englishName: 'Latvian' },
  { code: 'et', name: 'Estonski', englishName: 'Estonian' },
  { code: 'fa', name: 'Persijski', englishName: 'Persian' },
  { code: 'ur', name: 'Urdu', englishName: 'Urdu' },
  { code: 'sw', name: 'Svahili', englishName: 'Swahili' },
  { code: 'af', name: 'Afrikans', englishName: 'Afrikaans' },
  { code: 'zu', name: 'Zulu', englishName: 'Zulu' },
  { code: 'xh', name: 'Kosa', englishName: 'Xhosa' },
  { code: 'am', name: 'Amharski', englishName: 'Amharic' },
  { code: 'ga', name: 'Irski', englishName: 'Irish' },
  { code: 'cy', name: 'Velški', englishName: 'Welsh' },
  { code: 'is', name: 'Islandski', englishName: 'Icelandic' },
  { code: 'mt', name: 'Malteški', englishName: 'Maltese' },
];
